#!/usr/bin/env ruby

require 'rmagick'
puts Magick::Long_version
puts RUBY_VERSION

Dir.glob('*.rb').to_a.sort.each do |file|
  next if file == "util.rb"
  puts "** #{file} **"
  load "./#{file}"
end







